@url = https://8080-magenta-dormouse-4quoblpj.ws-us21.gitpod.io

###
GET {{url}}/filmes

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT {{url}}/filmes/4
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : 4
}